#+OPTIONS: ^:nil tags:nil num:nil

* About

Minor mode to format Emacs Lisp code.

* Table of Contents                                       :TOC_2_gh:QUOTE:
#+BEGIN_QUOTE
- [[#about][About]]
- [[#requirements][Requirements]]
- [[#installation][Installation]]
  - [[#with-use-package-and-straightel][With use-package and straight.el]]
  - [[#manual-installation][Manual installation]]
- [[#usage][Usage]]
- [[#customization][Customization]]
#+END_QUOTE

* Requirements

| Name  | Version |
|-------+---------|
| Emacs |    27.1 |


* Installation

** With use-package and straight.el
#+begin_src elisp :eval no
(use-package prettier-elisp
  :straight (prettier-elisp
             :type git
             :host github
             :repo "KarimAziev/prettier-elisp")
  :hook ((emacs-lisp-mode . prettier-elisp-mode)))
#+end_src

** Manual installation

Download the source code and put it wherever you like, e.g. into =~/.emacs.d/prettier-elisp/=

#+begin_src shell :eval no
git clone https://github.com/KarimAziev/prettier-elisp.git ~/.emacs.d/prettier-elisp/
#+end_src

Add the downloaded directory to the load path:

#+begin_src elisp :eval no
(add-to-list 'load-path "~/.emacs.d/prettier-elisp/")
(require 'prettier-elisp)
#+end_src

* Usage

- =M-x prettier-elisp-mode= - To enable automatic and manual formatting of Elisp code.
- =M-x prettier-elisp-buffer-mode= - To enable formatting whole buffer code before saving.
- =M-x prettier-elisp= - To manually format the current Emacs Lisp function definition.
- =M-x prettier-elisp-buffer= To manually format the whole bufer.

* Customization


#+begin_quote
[!NOTE]

You may want also to adjust the value of the variable =fill-column=.
#+end_quote

- ~prettier-elisp-buffer-post-format-hooks~ Hooks to run after formatting the whole buffer.
- ~prettier-elisp-pre-format-hooks~ Hooks to run before formatting.

